export const ADD_BLOCK_REQUEST = 'ADD_BLOCK_REQUESTS';
export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS';
export const ADD_BLOCK_FAILURE = 'ADD_BLOCK_FAILURE';

export const DELETE_BLOCK_REQUEST = 'DELETE_BLOCK_REQUEST';
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS';
export const DELETE_BLOCK_FAILURE = 'DELETE_BLOCK_FAILURE';