export const ADD_BUILDING_REQUEST = 'ADD_BUILDING_REQUESTS';
export const ADD_BUILDING_SUCCESS = 'ADD_BUILDING_SUCCESS';
export const ADD_BUILDING_FAILURE = 'ADD_BUILDING_FAILURE';

export const DELETE_BUILDING_REQUEST = 'DELETE_BUILDING_REQUEST';
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
export const DELETE_BUILDING_FAILURE = 'DELETE_BUILDING_FAILURE';